In [ ]:
# import tensorflow
import tensorflow as tf
print("version of tensorflow ", tf.__version__)

version of tensorflow  2.8.0


In [ ]:
# create tensor with tf.constant()
scaller = tf.constant(7)
scaller

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimansions of a tensor (ndim stands for number of dimensions)
scaller.ndim

0

In [ ]:
# create a vector 
vector = tf.constant([3,9])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 9], dtype=int32)>

In [ ]:
# check vector dimensios
vector.ndim

1

In [ ]:
# let's create matrix (more than one dimensions)
matrix = tf.constant([[3,9],
                     [9,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 9],
       [9, 3]], dtype=int32)>

In [ ]:
# check metrix dimension
matrix.ndim

2

In [ ]:
# create another matrix
another_metrix = tf.constant([[3,9],
                              [9,3],
                              [92,99]])
another_metrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  9],
       [ 9,  3],
       [92, 99]], dtype=int32)>

In [ ]:
# let's check how many dimension in another_metrix
another_metrix.ndim

2

In [ ]:
tf.shape(another_metrix)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [ ]:
# let's create tensor
tensor = tf.constant([[[1,2,3,7],[4,5,6,7]],
                      [[7,8,9,7],[10,11,12,7]],
                      [[13,14,15,7],[16,17,18,7]]])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  7],
        [ 4,  5,  6,  7]],

       [[ 7,  8,  9,  7],
        [10, 11, 12,  7]],

       [[13, 14, 15,  7],
        [16, 17, 18,  7]]], dtype=int32)>

In [ ]:
# let's check tensor dimension
tensor.ndim

3

* scalar: a single number.
* vector: a number with direction (e.g. wind speed with direction).
* matrix: a 2-dimensional array of numbers.
* tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

In [ ]:
# let's create tensor tf.Variable() and tf.constant()

# tf.Variable is when you try to change valu in this tensor that time you change 
changeble_tensor = tf.Variable([10,7])
unChangeble_tensor = tf.constant([10,7])
changeble_tensor,unChangeble_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# now you see change value in tensor but one problem that is not support assigment operator use assign method
changeble_tensor[0].assign(7)
changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# same is now i am try to change constant tensor throw error becuse this tensor doesn't chenge
# unChangeble_tensor[0].assign(1) this error show when you run this code AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'
# unChangeble_tensor[0] = 4 this error show whe n you run this code TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

### Creating Random Tensor

In [ ]:
# create two random tensor (but same value have this under)
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=[3,2])
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=[3,2])

random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# another way create random tensor
tf.random.set_seed(42)
un_random_1 = tf.random.uniform(shape=[3,3])
un_random_2 = tf.random.uniform(shape=[3,3])

un_random_1,un_random_2 , un_random_1 == un_random_2 

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 ],
        [0.252187  , 0.73115396, 0.89256823],
        [0.94674826, 0.7493341 , 0.34925628]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False, False, False]])>)

In [ ]:
# shuffle a tensor (valuable for when wan't to  shuffle data )

frist_random = tf.constant([[3,3],[4,4],[5,5]])
# evrey time different order work
tf.random.shuffle(frist_random)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 5],
       [4, 4],
       [3, 3]], dtype=int32)>

In [ ]:
second_random = tf.constant([[1,1],[2,2],[3,3]])
tf.random.shuffle(second_random,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [3, 3]], dtype=int32)>

In [ ]:
# now set global label seed now every time run this code same result show
tf.random.set_seed(42)
tf.random.shuffle(second_random) 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 3],
       [1, 1]], dtype=int32)>

## Another way make tensor 


In [ ]:
# create a tensor all element will be one
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# same is above but this time zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

🔑 **Note**: A matrix or tensor is typically represented by a capital letter (e.g. X or A) where as a vector is typically represented by a lowercase letter (e.g. y or b).

### Turn into numpy array into tensorflow tensor array

 - main differece between tensor and numpy array tensor run  can be (GPU faster numerical )



In [ ]:
import numpy as np
np_array = np.arange(0,24,dtype=int)
np_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# turn into tensor
tensor = tf.constant(np_array)
tensor ## hoooo now see tensor simple is that

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])>

In [ ]:
# shape modified
tensor = tf.constant(np_array,shape=[2,3,4]) # note: the shape total (2*4*3) has to match the number of elements in the array

tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

### Getting information from tensors (shape, rank, size)
There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:

* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* Axis or Dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor.

In [ ]:
# now see shape of tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# now see Rank of tensor 
rank_4_tensor.ndim

4

In [ ]:
# now see Axis or Dimensions of tensor
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# now see Size of tensor 
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
# now print all of this than look is good
print("Data type of every element: ",rank_4_tensor.dtype)
print("Number of Dimenstional (rank) :",rank_4_tensor.ndim)
print("Shape of tensor: ",rank_4_tensor.shape)
print("Element along 0 axis : ", rank_4_tensor.shape[0])
print("Element along last axis : ",rank_4_tensor.shape[-1])
print("Total Element size of tensor:",tf.size(rank_4_tensor))
print("Total Elment size of tensor (but this time convert to numpy): ",tf.size(rank_4_tensor).numpy())

Data type of every element:  <dtype: 'float32'>
Number of Dimenstional (rank) : 4
Shape of tensor:  (2, 3, 4, 5)
Element along 0 axis :  2
Element along last axis :  5
Total Element size of tensor: tf.Tensor(120, shape=(), dtype=int32)
Total Elment size of tensor (but this time convert to numpy):  120


### Index in tensor 
tensor index like a python list

In [ ]:
# now print every row choos 2 element
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# create frank 2 tensor 2 dimansionl
rank_2_tensor = tf.zeros(shape=[2,2])
rank_2_tensor,rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>, 2)

In [ ]:
# get the last element of each rank 2 tensor 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

You can also add dimensions to your tensor whilst keeping the same information present using tf.newaxis.

In [ ]:
# add extra dimanstion (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [ ]:
# another way to create extra dimandtion 
tf.expand_dims(rank_2_tensor,axis=-1) # same result above 

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [ ]:
# now axis is 0 than see
tf.expand_dims(rank_2_tensor,axis=0) # first 

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]]], dtype=float32)>

In [ ]:
# now axis is one
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[0., 0.]],

       [[0., 0.]]], dtype=float32)>

### Manipluting tensor (tensor operation)
#### Basic operation `+`,`-`,`*`,`/`

In [ ]:
# multiplication , additatio, subtraction, divide
tensor = tf.constant([[3,9],[33,99]])
tensor * 10, tensor + 10, tensor - 10, tensor/10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 30,  90],
        [330, 990]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 13,  19],
        [ 43, 109]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-7, -1],
        [23, 89]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[0.3, 0.9],
        [3.3, 9.9]])>)

In [ ]:
# same use in tensorflow buil-in-function but this time use GPU than lot faster than python operator
tf.multiply(tensor,10), tf.add(tensor,10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 30,  90],
        [330, 990]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 13,  19],
        [ 43, 109]], dtype=int32)>)

In [ ]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-7, -1],
       [23, 89]], dtype=int32)>

In [ ]:
tf.divide(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.3, 0.9],
       [3.3, 9.9]])>

In [ ]:
# but not change orginal tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  9],
       [33, 99]], dtype=int32)>

### Matrix mutliplication
One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:
   * (3, 5) @ (3, 5) won't work
   * (5, 3) @ (3, 5) will work
   * (3, 5) @ (5, 3) will work
2. The resulting matrix has the shape of the outer dimensions:

  * (5, 3) @ (3, 5) -> (5, 5)

  * (3, 5) @ (5, 3) -> (3, 3)

🔑 **Note**: '@' in Python is the symbol for matrix multiplication.



In [ ]:
# matrix multiplication in tensor flow function use
print(tensor)
tensor_2 = tf.constant([[3,9],[9,3]])
tf.matmul(tensor,tensor_2)

tf.Tensor(
[[ 3  9]
 [33 99]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 90,  54],
       [990, 594]], dtype=int32)>

In [ ]:
tensor_1 = tf.constant([[1,2,1],[0,1,0],[2,3,4]])
tensor_2 = tf.constant([[2,5],[6,7] ,[1,8]])
tensor_1,tensor_2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 1],
        [0, 1, 0],
        [2, 3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
# now multiplication to tensor function
tf.matmul(tensor_1,tensor_2) 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [ ]:
# now multiplication to python style
tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [ ]:
# create (3,2) tensor 
tensor_1 = tf.constant([[3,3],[4,2],[5,6]])

# create (3,2) tensor
tensor_2 = tf.constant([[3,2],[4,6],[3,3]])

# shape see
tensor_1.shape,tensor_2.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [ ]:
# now try to multiply to matrix but 2 different way one tensorflow way and another pythor way
# frist way tensor flow and show error
# tf.matmul(tensor_1,tensor_2) run this code show this error InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]
# second way python style
#  tensor_1 @ tensor_2 run this code same error show above.

*tf*.reshape() - allows us to reshape a tensor into a defined shape.

tf.transpose() - switches the dimensions of a given tensor.

In [ ]:
# example of two function work transpose 
tensor_1,tf.transpose(tensor_1)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 3],
        [4, 2],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 4, 5],
        [3, 2, 6]], dtype=int32)>)

In [ ]:
# work on shape 
tensor_1, tf.reshape(tensor_1,shape=[2,3])

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 3],
        [4, 2],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 3, 4],
        [2, 5, 6]], dtype=int32)>)

### The dot product
Multiplying matrices by eachother is also referred to as the dot product.

You can perform the `tf.matmul()` operation using `tf.tensordot()`.



In [ ]:
# use tf.tensordot()
tf.tensordot(tf.transpose(tensor_1),tensor_2,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 45],
       [35, 36]], dtype=int32)>

In [ ]:
tf.tensordot(tf.reshape(tensor_1,shape=[2,3]),tensor_2,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[33, 36],
       [44, 52]], dtype=int32)>

In [ ]:
print("Normal tensor 1 : \n")
print(tensor_1)
print("Transpose tensor 1: ")
print(tf.transpose(tensor_1))
print("reshape tensor 1: ")
print(tf.reshape(tensor_1, shape=[2,3]))

Normal tensor 1 : 

tf.Tensor(
[[3 3]
 [4 2]
 [5 6]], shape=(3, 2), dtype=int32)
Transpose tensor 1: 
tf.Tensor(
[[3 4 5]
 [3 2 6]], shape=(2, 3), dtype=int32)
reshape tensor 1: 
tf.Tensor(
[[3 3 4]
 [2 5 6]], shape=(2, 3), dtype=int32)


### Changing the datatype of a tensor
Some time you alter defult dtype  of your tensor

This is common when you want to compute using less precision (e.g. 16-bit floating point numbers vs. 32-bit floating point numbers).

Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).

You can change the datatype of a tensor using tf.cast().

In [ ]:
# create defult tensorflow dtype32
A = tf.constant([3.0,3.4,4.3])
A.dtype

tf.float32

In [ ]:
B = tf.constant([3,4,5])
B.dtype

tf.int32

In [ ]:
# now change defult data type is  tf.int32 to tf.int16
B = tf.cast(B,dtype=tf.int16)
B

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([3, 4, 5], dtype=int16)>

In [ ]:
# now change defult data type is tf.float.32 to tf.float16
A = tf.cast(A, dtype=tf.float16)
A

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([3. , 3.4, 4.3], dtype=float16)>

In [ ]:
# you also change int32 to float32
C = tf.cast(B,dtype=tf.float32)
C

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 4., 5.], dtype=float32)>

### Getting the absolute value
some time all value to tensor will be positive

In [ ]:
D = tf.constant([-3,-2])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3, -2], dtype=int32)>

In [ ]:
# now get absolute value in tensor
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>


### Finding the min, max, mean, sum (aggregation)

1. minium value function is (`tf.reduce_min()`).
2. maximum value function is (`tf.reduce_max()`).
3. mean value function is (`tf.reduce_mean()`).
4. sum value function is (`tf.reduce_sum()`).


In [ ]:
# create random  tensor
tensor = tf.constant(np.random.randint(0,100,size=50))
tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([22, 64, 95, 74, 79, 66, 38, 81, 59, 26, 60, 49,  8, 92, 88, 48, 99,
       57, 52, 40, 94, 48, 67, 32, 22, 85, 24,  8, 50,  3, 25, 87, 38,  5,
       75, 97, 10, 23, 88, 79, 84, 95, 15, 18,  9, 19, 37, 76, 55, 72])>

In [ ]:
# get minimum value tensor
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [ ]:
# get maximum value in tensor
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# gen mean value in  tensor
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [ ]:
# get sum value in tensor
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2637>

In [ ]:
# use standard division in tensorflow 
tensor = tf.cast(tensor,dtype=tf.float32)
tf.math.reduce_std(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=29.645782>

In [ ]:
# find the tensorflow varieance in tenosorflow probability
import tensorflow_probability as tfp
tfp.stats.variance(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=878.87244>

In [ ]:
# create new tensor 
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find positional maximum value in tensor
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# find the maxium value get in index
print(tensor[tf.argmax(tensor)])

tf.Tensor(0.9671384, shape=(), dtype=float32)


In [ ]:
# find positional minimum value in tensor
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# find the index of minimum value
tensor[tf.argmin(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Sequeezing in tensor (Removing all single dimansional)
i am use this function to remove single dimansional and another name is sequeezing `tf.squeeze()`.

In [ ]:
# create new tensor allways start with new tensor
# set random seed 
tf.random.set_seed(42)
tensor_3 = tf.random.uniform(shape=[1,1,1,1,50])
tensor_3

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
# now remove all single dimansional
squeez_tensor = tf.squeeze(tensor_3)
squeez_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# One hot encoding

if you have tensor indeces and would like to one-hot-encoding , use this function - `tf.one_hot()`.

must be specify depth value in ond_hot function under

In [ ]:
# create new one hot endeces
color = [0,1,2] # 0 -> red ,1 -> green, 2 -> blue
# now convert to tensor one hot encoding format
tf.one_hot(color,depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
# create new one hot endeces but this time see one value and off value
color = [0,1,2] # same this above code
# now convert to tensor one hot encoding format
tf.one_hot(color,depth=3,on_value="I like deep learning",off_value="I like machine leanring")

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'I like deep learning', b'I like machine leanring',
        b'I like machine leanring'],
       [b'I like machine leanring', b'I like deep learning',
        b'I like machine leanring'],
       [b'I like machine leanring', b'I like machine leanring',
        b'I like deep learning']], dtype=object)>

### Squaring , log,squar root
many other math function have in tensorflow allways exeperiment

In [ ]:
# create new tensor
tensor = tf.range(0,10)
tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# now squaring math function use
tf.square(tensor)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# now squar root math function use
# all ways every tensor must be type of this : (bfloat16, half, float32, float64, complex64, complex128)
# tf.sqrt(tensor) this line run than error show becuse this tensor type is int32
tf.sqrt(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.        , 0.99999994, 1.4142134 , 1.7320508 , 1.9999999 ,
       2.236068  , 2.4494896 , 2.6457512 , 2.828427  , 3.        ],
      dtype=float32)>

In [ ]:
# now loog math function use
# all ways every tensor must be type of this: (bfloat16, half, float32, float64, complex64, complex128.)
# tf.math.log(tensor) this line code error throw becuse this tensor type is int32
tf.math.log(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensor And Numpy
We have interect tensor to numpy array some time create tensor array directly use number

In [ ]:
# create tensor with numpy array 
tensor_numpy = tf.constant(np.array([3.,7.,9.]))
tensor_numpy

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 7., 9.])>

In [ ]:
# create tensor directly in tensor
tensor = tf.constant([3.,7.,9.])
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 7., 9.], dtype=float32)>

In [ ]:
# tensor and numpy different of defult data type
tensor_numpy = tf.constant(np.array([3.,7.,9.])) # numpy array defult datatype is float64
tensor = tf.constant([3.,7.,9.]) # tensor defult datatype is float32
# check two tensor  data type
tensor_numpy.dtype, tensor.dtype

(tf.float64, tf.float32)